#!/bin/bash

# Find out where we are:
SCRIPT=$(readlink -f "$BASH_SOURCE")
MYPATH="${SCRIPT%/*}"
# Our config files:
XSLTFILES_CONFIG=$MYPATH/xsltfiles.txt
IGNOREFILE_CONFIG=$MYPATH/ignore-xslt.txt

# Assign RELAX NG
RNG="$MYPATH/xslt10.rnc"

echo $RNG
if [[ ! -e $RNG ]]; then
 echo "Couldn't find the RNG schema"
 exit 10
fi

function readfilecfg() {
    # Read lines from a file while avoiding lines with #
    local RESULT=""
    local LINE
    local FILEINPUT=$1
    while read -r LINE; do
      [[ "$LINE" =~ ^#.*$ ]] && continue;
      RESULT="$RESULT $LINE";
    done < $FILEINPUT
    echo $RESULT
}

# These are the directories to investigate:
XSLTFILES=$(readfilecfg $XSLTFILES_CONFIG)

# Fill the ignore list
IGNORE="$(readfilecfg $IGNOREFILE_CONFIG)"

for ign in $IGNORE; do
    XSLTFILES=$(echo $XSLTFILES | sed -e "s#$ign##g")
done

result=0
for xslt in $XSLTFILES; do
  echo -n "> Validating $xslt..."
  jing -c $RNG $xslt
  r=$?
  [[ $r -eq 0 ]] && echo "ok"
  [[ $r -eq 0 ]] || result=1
done

exit $result
